language: php

php:
  - 7.0
  - 7.1
  - 7.2

sudo: false

env:
  matrix:
    - COMPOSER_FLAGS=""

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --dev

script:
  - vendor/bin/phpunit
